### PR TITLE
Bump version to 2.0.0.0

### PR DESCRIPTION
**Pull request by quantumagi**

### CODE REVIEW

**Comment by quantumagi** [comment]
@YakupIpek , @fassadlr , we probably need upgraded NuGet's for:
- Stratis.SmartContracts.Core
- Stratis.SmartContracts.Network

as well. The code is found as part of the full node in the StratisFullNode repository.

image

**Comment by quantumagi** [comment]
We should not release this code until a sufficient number of nodes have upgraded to PR 365: stratisproject/StratisFullNode#365.

**Comment by YakupIpek** [comment]
IMO yes we should update those packages @quantumagi 

> @YakupIpek , @fassadlr , we probably need upgraded NuGet's for:
> 
> * Stratis.SmartContracts.Core
> * Stratis.SmartContracts.Network
> 
> as well. The code is found as part of the full node in the StratisFullNode repository.

**Comment by YakupIpek** [comment]
Atm compilations fails for new contracts because of those packages.

**Comment by YakupIpek** [comment]
Also versioning is need for the project and current version is actually v0.0.2 and we can bump it to v0.0.3

**Comment by quantumagi** [comment]
https://github.com/stratisproject/StratisFullNode/pull/365#issuecomment-769617746

**Comment by quantumagi** [comment]
Just waiting for NuGet packages to upgrade this.

**Comment by quantumagi** [comment]
@YakupIpek , packages are upgraded and version bumped. Please review/approve.

**Review by YakupIpek — APPROVED** [review]
It looks good to me 

Just update version on VersionOption attribute in Program.cs file.

**Review by fassadlr — APPROVED** [review]

**Comment by quantumagi** [comment]
First merge the full node PR. The core package reference will require updating.

**Pull request merged**
